`ifndef POTADOS_SV
`define POTADOS_SV

`timescale 1ns / 1ps
`include "potados_common.sv"
`include "potados_instruction_decoder.sv"
`include "potados_registers.sv"
`include "potados_scoreboard.sv"
`include "potados_alu.sv"
`include "potados_memory.sv"
`include "potados_execute.sv"


module potados_memory_stage(
    input memory_stage_t memory_stage,

    output logic [15:0] ram_address,
    output logic        ram_store_enable,
    output logic [15:0] ram_store_data,
    output logic        ram_load_enable,
    input  logic [15:0] ram_load_data,
    
    output writeback_stage_t writeback_stage,
    output logic should_stall
);

    always_comb begin
        ram_address = memory_stage.alu_result;
        ram_store_enable = memory_stage.valid && (memory_stage.memory_op == MEMORY_STORE);
        ram_store_data = memory_stage.memory_write_data;
        ram_load_enable = memory_stage.valid && (memory_stage.memory_op == MEMORY_LOAD);

        writeback_stage = '0;
        writeback_stage.valid = memory_stage.valid;
        writeback_stage.alu_result = memory_stage.alu_result;
        writeback_stage.memory_write_data = memory_stage.memory_write_data;
        writeback_stage.fpu_result = memory_stage.fpu_result;
        writeback_stage.next_pc = memory_stage.next_pc;
        writeback_stage.dst = memory_stage.dst;
        writeback_stage.stack_pointer_op = memory_stage.stack_pointer_op;
        writeback_stage.writeback_source = memory_stage.writeback_source;
        should_stall = 1'b0;
    end
endmodule

module potados_writeback_stage(
    input writeback_stage_t writeback_stage,

    output register_write_request_t register_write_request,
    output stack_pointer_request_t  stack_pointer_request
);
    always_comb begin
        register_write_request.write_enable = writeback_stage.valid
            && (writeback_stage.writeback_source != WB_NONE);
        register_write_request.write_address = writeback_stage.dst;

        case (writeback_stage.writeback_source)
            WB_NONE: register_write_request.write_data = '0;
            WB_ALU:  register_write_request.write_data = writeback_stage.alu_result;
            WB_FPU:  register_write_request.write_data = writeback_stage.fpu_result;
            WB_MEMORY:  register_write_request.write_data = writeback_stage.memory_write_data;
            WB_RETURN_ADDRESS:   register_write_request.write_data = writeback_stage.next_pc;
            default: register_write_request.write_data = '0;
        endcase

        stack_pointer_request.operation = writeback_stage.valid
            ? writeback_stage.stack_pointer_op
            : STACK_POINTER_NONE;
        stack_pointer_request.write_data = '0; // TODO
    end
endmodule

module potados #(
    parameter ROM_FILE = "rom.hex",
    parameter LOAD_ROM_FILE = 1'b1
)(
    input logic clk,
    input logic reset,
    output register_file_t registers_out,
    output logic halt_out,
    output logic[15:0] pc_out
);
    // Fetched instruction words and their validity flags.
    logic [15:0] fetched_instruction_low;
    logic [15:0] fetched_instruction_high;
    logic [15:0] fetched_instruction_pc;
    logic [15:0] fetched_instruction_next_pc;
    logic        fetched_instruction_valid;
    logic        fetched_high_valid;

    // Decoded form of the fetched instruction.
    decoded_instruction_t decoded_instruction;

    // Requests sent to the instruction-fetch unit.
    logic fetch_low_word_request;
    logic fetch_low_word_request_next;

    // Requests for long instructions: JUMP ect.
    logic fetch_high_word_request;
    logic fetch_high_word_request_next;

    // Jump control signals generated by the execute stage.
    logic jump_enable;
    logic [15:0] jump_address;

    // Halt signal generated by the execute stage.
    logic halt;

    // Memory control signals generated by the execute stage.
    logic[15:0] ram_address;
    logic       ram_store_enable;
    logic[15:0] ram_store_data;
    logic       ram_load_enable;
    logic[15:0] ram_load_data;

    register_file_t registers;
    register_status_t register_status;

    logic decode_declare_stall;
    logic execute_declare_stall;
    logic memory_declare_stall;
    logic writeback_declare_stall;
    pipeline_stall_t pipeline_stall;

    execute_stage_t execute_stage;
    execute_stage_t execute_stage_next;

    memory_stage_t memory_stage;
    memory_stage_t memory_stage_next;

    writeback_stage_t writeback_stage;
    writeback_stage_t writeback_stage_next;

    // Register-file interfaces shared by decode and writeback.

    // Request that sets the register read addresses for the current instruction.
    register_read_request_t register_read_request;
    // Response that provides the register read data for the current instruction.
    register_read_response_t register_read_response;
    // Request that sets the register write address and data for the current instruction.
    register_write_request_t register_write_request;
    // Request that sets the stack pointer update logic for the current instruction.
    stack_pointer_request_t stack_pointer_request;
    // Scoreboard inputs are masks because POP can reserve both DST and SP.
    logic [7:0] scoreboard_reserve_write_mask;
    logic [7:0] scoreboard_release_write_mask;
    logic       decode_accept;


    potados_program_memory #(
        .ROM_FILE(ROM_FILE),
        .LOAD_ROM_FILE(LOAD_ROM_FILE)
    ) program_memory_inst (
        .clk(clk),
        .reset(reset),
        
        .request_long_instruction(fetch_high_word_request),
        .request_next_instruction(fetch_low_word_request),
        
        .jump_address(jump_address),
        .jump_enable(jump_enable),
        
        .low_instruction(fetched_instruction_low),
        .high_instruction(fetched_instruction_high),
        .instruction_pc(fetched_instruction_pc),

        .high_valid(fetched_high_valid),

        .low_valid(fetched_instruction_valid)
    );

    potados_instruction_decoder instruction_decoder_inst (
        .instruction_low(fetched_instruction_low),
        .instruction_high(fetched_instruction_high),
        .high_valid(fetched_high_valid),
        
        .decoded_instruction(decoded_instruction)
    );

    assign fetched_instruction_next_pc = fetched_instruction_pc + (decoded_instruction.is_long ? 16'd2 : 16'd1);

    potados_decode_stage decode_stage_inst (
        .instruction_valid(fetched_instruction_valid),
        .instruction_pc(fetched_instruction_pc),
        .instruction_next_pc(fetched_instruction_next_pc), // Check if that's needed
        .decoded_instruction(decoded_instruction),

        .register_read_request(register_read_request),
        .register_read_response(register_read_response),
        .register_status(register_status),

        .should_stall(decode_declare_stall),

        .execute_stage(execute_stage_next)
    );

    potados_execute_stage execute_stage_inst (
        .clk(clk),
        .reset(reset),
        .execute_stage(execute_stage),
        .fpu_output(16'h0000),
        
        .memory_stage(memory_stage_next),
        .should_stall(execute_declare_stall),

        .jump_enable(jump_enable), 
        .jump_address(jump_address),
        .halt(halt) 
    );

    potados_memory_stage memory_stage_inst (
        .memory_stage(memory_stage),

        .ram_address(ram_address),
        .ram_store_enable(ram_store_enable),
        .ram_store_data(ram_store_data),
        .ram_load_enable(ram_load_enable),
        .ram_load_data(ram_load_data),

        .writeback_stage(writeback_stage_next),
        .should_stall(memory_declare_stall)
    );

    potados_writeback_stage writeback_stage_inst (
        .writeback_stage(writeback_stage),
        .register_write_request(register_write_request),
        .stack_pointer_request(stack_pointer_request)
    );

    potados_registers registers_inst (
        .clk(clk),
        .reset(reset),
        .read_request(register_read_request),
        .read_response(register_read_response),
        .write_request(register_write_request),
        .stack_pointer_request(stack_pointer_request),

        .registers(registers)
    );

    // Decode reserves every future register/SP write at the same edge that
    // accepts the instruction into execute. Writeback releases reservations
    // when the corresponding architectural updates commit.
    always_comb begin
        decode_accept = execute_stage_next.valid
            && !decode_declare_stall
            && (pipeline_stall == PIPELINE_STALL_NONE);

        scoreboard_reserve_write_mask = '0;
        if (decode_accept) begin
            if (execute_stage_next.writeback_source != WB_NONE) begin
                scoreboard_reserve_write_mask[execute_stage_next.dst] = 1'b1;
            end
            if (execute_stage_next.stack_pointer_op != STACK_POINTER_NONE) begin
                scoreboard_reserve_write_mask[3'b001] = 1'b1;
            end
        end
        scoreboard_reserve_write_mask[3'b000] = 1'b0;

        scoreboard_release_write_mask = '0;
        if (register_write_request.write_enable) begin
            scoreboard_release_write_mask[register_write_request.write_address] = 1'b1;
        end
        if (stack_pointer_request.operation != STACK_POINTER_NONE) begin
            scoreboard_release_write_mask[3'b001] = 1'b1;
        end
        scoreboard_release_write_mask[3'b000] = 1'b0;
    end

    potados_scoreboard scoreboard_inst (
        .clk(clk),
        .reset(reset),
        .reserve_write_mask(scoreboard_reserve_write_mask),
        .release_write_mask(scoreboard_release_write_mask),
        .register_status(register_status)
    );

    potados_memory potados_memory (
        .clk         (clk),
        .address     (ram_address),
        .store_enable(ram_store_enable),
        .store_data  (ram_store_data),
        .load_enable (ram_load_enable),
        .load_data   (ram_load_data)
    );

    always_ff @(posedge clk or posedge reset) begin
        if (reset) begin
            fetch_low_word_request <= 1'b1;
            fetch_high_word_request <= 1'b0;
            execute_stage <= '0;
            memory_stage <= '0;
            writeback_stage <= '0;
        end else begin
            case (pipeline_stall)
                PIPELINE_STALL_NONE: begin
                    execute_stage   <= execute_stage_next;
                    memory_stage    <= memory_stage_next;
                    writeback_stage <= writeback_stage_next;
                end

                PIPELINE_STALL_EXECUTE: begin
                    // Execute retains its instruction.
                    // Older memory/writeback instructions continue draining.
                    execute_stage   <= execute_stage;
                    memory_stage    <= '0;
                    writeback_stage <= writeback_stage_next;
                end

                PIPELINE_STALL_MEMORY: begin
                    // Memory cannot accept another execute result.
                    execute_stage   <= execute_stage;
                    memory_stage    <= memory_stage;
                    writeback_stage <= '0;
                end

                PIPELINE_STALL_WRITEBACK: begin
                    // Nothing downstream can accept another instruction.
                    execute_stage   <= execute_stage;
                    memory_stage    <= memory_stage;
                    writeback_stage <= writeback_stage;
                end

                default: begin
                    execute_stage   <= execute_stage;
                    memory_stage    <= memory_stage;
                    writeback_stage <= writeback_stage;
                end
            endcase
            fetch_low_word_request <= fetch_low_word_request_next;
            fetch_high_word_request <= fetch_high_word_request_next;
        end
    end

    always_comb begin
        pipeline_stall = PIPELINE_STALL_NONE;
        if (writeback_declare_stall) begin
            pipeline_stall = PIPELINE_STALL_WRITEBACK;
        end else if (memory_declare_stall) begin
            pipeline_stall = PIPELINE_STALL_MEMORY;
        end else if (execute_declare_stall) begin
            pipeline_stall = PIPELINE_STALL_EXECUTE;
        end
    end

    always_comb begin
        fetch_high_word_request_next = 1'b0;
        fetch_low_word_request_next = 1'b0;

        if (fetched_instruction_valid && halt == 1'b0) begin
            if (decoded_instruction.is_long && decoded_instruction.partialy_decoded) begin
                fetch_high_word_request_next = 1'b1;
            end else begin
                fetch_low_word_request_next = 1'b1;
            end
        end
    end

    assign registers_out = registers;
    assign halt_out = halt;
    assign pc_out = fetched_instruction_pc;

endmodule

`endif
