`ifndef POTADOS_SV
`define POTADOS_SV

`timescale 1ns / 1ps
`include "potados_common.sv"
`include "potados_instruction_decoder.sv"
`include "potados_registers.sv"
`include "potados_alu.sv"
`include "potados_memory.sv"
`include "potados_execute.sv"


module potados_memory_stage(
    input logic clk,
    input logic reset,
    
    input memory_stage_t memory_stage


);



endmodule


module potados(
    input logic clk,
    input logic reset,
    output logic [15:0] low_instruction_out,
    output logic [15:0] high_instruction_out,
    output logic instruction_is_long,
    output logic instruction_ready,
    output decoded_instruction_t decoded_instruction_out,
    output register_file_t registers_out
);
    // Fetched instruction words and their validity flags.
    logic [15:0] fetched_instruction_low;
    logic [15:0] fetched_instruction_high;
    logic [15:0] fetched_instruction_pc;
    logic [15:0] fetched_instruction_next_pc;
    logic        fetched_instruction_valid;
    logic        fetched_high_valid;

    // Decoded form of the fetched instruction.
    decoded_instruction_t decoded_instruction;

    // Requests sent to the instruction-fetch unit.
    logic fetch_low_word_request;
    logic fetch_low_word_request_next;

    // Requests for long instructions: JUMP ect.
    logic fetch_high_word_request;
    logic fetch_high_word_request_next;

    // Jump control signals generated by the execute stage.
    logic jump_enable;
    logic [15:0] jump_address;

    // Halt signal generated by the execute stage.
    logic halt;

    // Memory control signals generated by the execute stage.
    logic 




    register_file_t registers;

    execute_stage_t execute_stage;
    execute_stage_t execute_stage_next;

    memory_stage_t memory_stage;
    memory_stage_t memory_stage_next;

    writeback_stage_t writeback_stage;
    writeback_stage_t writeback_stage_next;

    // Register-file interfaces shared by decode and writeback.

    // Request that sets the register read addresses for the current instruction.
    register_read_request_t register_read_request;
    // Response that provides the register read data for the current instruction.
    register_read_response_t register_read_response;
    // Request that sets the register write address and data for the current instruction.
    register_write_request_t register_write_request = '0; // TODO
    // Request that sets the stack pointer update logic for the current instruction.
    stack_pointer_request_t stack_pointer_request = '0; // TODO

    potados_program_memory program_memory_inst (
        .clk(clk),
        .reset(reset),
        
        .request_long_instruction(fetch_high_word_request),
        .request_next_instruction(fetch_low_word_request),
        
        .jump_address(16'b0),
        .jump_enable(1'b0),
        
        .low_instruction(fetched_instruction_low),
        .high_instruction(fetched_instruction_high),
        .instruction_pc(fetched_instruction_pc),

        .high_valid(fetched_high_valid),

        .low_valid(fetched_instruction_valid)
    );

    potados_instruction_decoder instruction_decoder_inst (
        .instruction_low(fetched_instruction_low),
        .instruction_high(fetched_instruction_high),
        .high_valid(fetched_high_valid),
        
        .decoded_instruction(decoded_instruction)
    );

    // TODO: Check if this wire is correct and needed.
    assign fetched_instruction_next_pc = fetched_instruction_pc + (decoded_instruction.is_long ? 16'd2 : 16'd1);

    potados_decode_stage decode_stage_inst (
        .instruction_valid(fetched_instruction_valid),
        .instruction_pc(fetched_instruction_pc),
        .instruction_next_pc(fetched_instruction_next_pc), // Check if that's needed
        .decoded_instruction(decoded_instruction),

        .register_read_request(register_read_request),
        .register_read_response(register_read_response),

        .execute_stage(execute_stage_next)
    );

    potados_execute_stage execute_stage_inst (
        .clk(clk),
        .reset(reset),
        .execute_stage(execute_stage),
        .memory_stage(memory_stage_next),
        .jump_enable(jump_enable), 
        .jump_address(jump_address),
        .halt(halt) 
    );

    potados_registers registers_inst (
        .clk(clk),
        .reset(reset),
        .read_request(register_read_request),
        .read_response(register_read_response),
        .write_request(register_write_request),
        .stack_pointer_request(stack_pointer_request),

        .registers(registers)
    );




    potados_memory potados_memory (
        .clk         (clk),
        .address     (address),
        .store_enable(store_enable),
        .store_data  (store_data),
        .load_enable (load_enable),
        .load_data   (load_data)
    );

    always_ff @(posedge clk or posedge reset) begin
        if (reset) begin
            fetch_low_word_request <= 1'b1;
            fetch_high_word_request <= 1'b0;
            execute_stage <= '0;
            memory_stage <= '0;
            writeback_stage <= '0;
        end else begin
            fetch_low_word_request <= fetch_low_word_request_next;
            fetch_high_word_request <= fetch_high_word_request_next;
            execute_stage <= execute_stage_next;
        end
    end

    always_comb begin
        fetch_high_word_request_next = 1'b0;
        fetch_low_word_request_next = 1'b0;

        if (fetched_instruction_valid && halt == 1'b0) begin
            if (decoded_instruction.is_long && decoded_instruction.partialy_decoded) begin
                fetch_high_word_request_next = 1'b1;
            end else begin
                fetch_low_word_request_next = 1'b1;
            end
        end
    end

    assign instruction_ready = fetched_instruction_valid;
    assign instruction_is_long = decoded_instruction.is_long;
    assign low_instruction_out = fetched_instruction_low;
    assign high_instruction_out = fetched_instruction_high;
    assign decoded_instruction_out = decoded_instruction;
    assign registers_out = registers;
endmodule

`endif
