`ifndef POTADOS_SV
`define POTADOS_SV

`timescale 1ns / 1ps
`include "potados_common.sv"
`include "potados_instruction_decoder.sv"
`include "potados_registers.sv"
`include "potados_alu.sv"
`include "potados_memory.sv"
`include "potados_execute.sv"


module potados_memory_stage(
    input memory_stage_t memory_stage,

    output logic [15:0] ram_address,
    output logic        ram_store_enable,
    output logic [15:0] ram_store_data,
    output logic        ram_load_enable,
    input  logic [15:0] ram_load_data,
    
    output writeback_stage_t writeback_stage
);

    always_comb begin
        ram_address = memory_stage.alu_result;
        ram_store_enable = (memory_stage.memory_op == MEMORY_STORE);
        ram_store_data = memory_stage.memory_write_data;
        ram_load_enable = (memory_stage.memory_op == MEMORY_LOAD);

        writeback_stage.valid = memory_stage.valid;
        writeback_stage.dst = memory_stage.dst;
    end
endmodule

module potados_writeback_stage(
    input writeback_stage_t writeback_stage,

    output register_write_request_t register_write_request,
    output stack_pointer_request_t  stack_pointer_request
);
    always_comb begin
        register_write_request.write_enable = writeback_stage.valid;
        register_write_request.write_address = writeback_stage.dst;

        case (writeback_stage.writeback_source)
            WB_NONE: register_write_request.write_data = '0;
            WB_ALU:  register_write_request.write_data = writeback_stage.alu_result;
            WB_FPU:  register_write_request.write_data = writeback_stage.fpu_result;
            WB_MEMORY:  register_write_request.write_data = writeback_stage.memory_write_data;
            WB_RETURN_ADDRESS:   register_write_request.write_data = writeback_stage.next_pc;
            default: register_write_request.write_data = '0;
        endcase

        // TODO: Do it later.
        stack_pointer_request.operation = writeback_stage.stack_pointer_op;
        stack_pointer_request.write_data = '0; // TODO
    end
endmodule

module potados(
    input logic clk,
    input logic reset,
    output register_file_t registers_out,
    output logic halt_out,
    output logic[15:0] pc_out
);
    // Fetched instruction words and their validity flags.
    logic [15:0] fetched_instruction_low;
    logic [15:0] fetched_instruction_high;
    logic [15:0] fetched_instruction_pc;
    logic [15:0] fetched_instruction_next_pc;
    logic        fetched_instruction_valid;
    logic        fetched_high_valid;

    // Decoded form of the fetched instruction.
    decoded_instruction_t decoded_instruction;

    // Requests sent to the instruction-fetch unit.
    logic fetch_low_word_request;
    logic fetch_low_word_request_next;

    // Requests for long instructions: JUMP ect.
    logic fetch_high_word_request;
    logic fetch_high_word_request_next;

    // Jump control signals generated by the execute stage.
    logic jump_enable;
    logic [15:0] jump_address;

    // Halt signal generated by the execute stage.
    logic halt;

    // Memory control signals generated by the execute stage.
    logic[15:0] ram_address;
    logic       ram_store_enable;
    logic[15:0] ram_store_data;
    logic       ram_load_enable;
    logic[15:0] ram_load_data;

    register_file_t registers;

    logic pipeline_stall = '0;

    execute_stage_t execute_stage;
    execute_stage_t execute_stage_next;

    memory_stage_t memory_stage;
    memory_stage_t memory_stage_next;

    writeback_stage_t writeback_stage;
    writeback_stage_t writeback_stage_next;

    // Register-file interfaces shared by decode and writeback.

    // Request that sets the register read addresses for the current instruction.
    register_read_request_t register_read_request;
    // Response that provides the register read data for the current instruction.
    register_read_response_t register_read_response;
    // Request that sets the register write address and data for the current instruction.
    register_write_request_t register_write_request;
    // Request that sets the stack pointer update logic for the current instruction.
    stack_pointer_request_t stack_pointer_request;

    potados_program_memory program_memory_inst (
        .clk(clk),
        .reset(reset),
        
        .request_long_instruction(fetch_high_word_request),
        .request_next_instruction(fetch_low_word_request),
        
        .jump_address(16'b0),
        .jump_enable(1'b0),
        
        .low_instruction(fetched_instruction_low),
        .high_instruction(fetched_instruction_high),
        .instruction_pc(fetched_instruction_pc),

        .high_valid(fetched_high_valid),

        .low_valid(fetched_instruction_valid)
    );

    potados_instruction_decoder instruction_decoder_inst (
        .instruction_low(fetched_instruction_low),
        .instruction_high(fetched_instruction_high),
        .high_valid(fetched_high_valid),
        
        .decoded_instruction(decoded_instruction)
    );

    // TODO: Check if this wire is correct and needed.
    assign fetched_instruction_next_pc = fetched_instruction_pc + (decoded_instruction.is_long ? 16'd2 : 16'd1);

    potados_decode_stage decode_stage_inst (
        .instruction_valid(fetched_instruction_valid),
        .instruction_pc(fetched_instruction_pc),
        .instruction_next_pc(fetched_instruction_next_pc), // Check if that's needed
        .decoded_instruction(decoded_instruction),

        .register_read_request(register_read_request),
        .register_read_response(register_read_response),

        .execute_stage(execute_stage_next)
    );

    // TODO: Think about how to handle FPU output,
    // 1) Stall pipeline
    // 2) Add flag to registers that indicate FPU is busy and stall pipeline on read from this register
    // 3) ???
    // Ok this is global problem, same thing with memory and Execute state:
    // We must stall pipeline when someone tries to read from register that was not written by previous stage yet. So we need to add some kind of "ready" flag to writeback stage and check it in decode stage.
    potados_execute_stage execute_stage_inst (
        .clk(clk),
        .reset(reset),
        .execute_stage(execute_stage),
        
        .memory_stage(memory_stage_next),

        .jump_enable(jump_enable), 
        .jump_address(jump_address),
        .halt(halt) 
    );

    potados_memory_stage memory_stage_inst (
        .memory_stage(memory_stage),

        .ram_address(ram_address),
        .ram_store_enable(ram_store_enable),
        .ram_store_data(ram_store_data),
        .ram_load_enable(ram_load_enable),
        .ram_load_data(ram_load_data),

        .writeback_stage(writeback_stage_next)
    );

    potados_registers registers_inst (
        .clk(clk),
        .reset(reset),
        .read_request(register_read_request),
        .read_response(register_read_response),
        .write_request(register_write_request),
        .stack_pointer_request(stack_pointer_request),

        .registers(registers)
    );

    potados_memory potados_memory (
        .clk         (clk),
        .address     (ram_address),
        .store_enable(ram_store_enable),
        .store_data  (ram_store_data),
        .load_enable (ram_load_enable),
        .load_data   (ram_load_data)
    );

    potados_writeback_stage writeback_stage_inst (
        .writeback_stage(writeback_stage),
        .register_write_request(register_write_request),
        .stack_pointer_request(stack_pointer_request)
    );

    always_ff @(posedge clk or posedge reset) begin
        if (reset) begin
            fetch_low_word_request <= 1'b1;
            fetch_high_word_request <= 1'b0;
            execute_stage <= '0;
            memory_stage <= '0;
            writeback_stage <= '0;
        end else begin
            if(pipeline_stall == 1'b0) begin
                execute_stage <= execute_stage_next;
                memory_stage <= memory_stage_next;
                writeback_stage <= writeback_stage_next;
            end else begin
                execute_stage <= execute_stage;
                memory_stage <= memory_stage;
                writeback_stage <= writeback_stage;
            end
            fetch_low_word_request <= fetch_low_word_request_next;
            fetch_high_word_request <= fetch_high_word_request_next;
        end
    end

    always_comb begin
        fetch_high_word_request_next = 1'b0;
        fetch_low_word_request_next = 1'b0;

        if (fetched_instruction_valid && halt == 1'b0) begin
            if (decoded_instruction.is_long && decoded_instruction.partialy_decoded) begin
                fetch_high_word_request_next = 1'b1;
            end else begin
                fetch_low_word_request_next = 1'b1;
            end
        end
    end

    assign registers_out = registers;
    assign halt_out = halt;
    assign pc_out = fetched_instruction_pc;

endmodule

`endif
