[project]
name = "potados-chilled"
version = "0.1.0"
description = "Simple Tang Nano 20K FPGA starter project"
readme = "README.md"
requires-python = "==3.13"
dependencies = [
    "cocotb>=2.0.1",
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
python_files = ["test_*.py"]
pythonpath = ["asm/src"]
testpaths = ["tb", "asm/tests"]
